# Docker Compose

version: '3.9'

services:
  api:
    build:
      context: ..
      dockerfile: docker/api.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=dev
    volumes:
      - ../src:/app/src
    command: ["uvicorn", "src.{{ cookiecutter.package_name }}.api.app:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  job:
    build:
      context: ..
      dockerfile: docker/job.Dockerfile
    environment:
      - APP_ENV=dev
    volumes:
      - ../src:/app/src
    command: ["python", "src/{{ cookiecutter.package_name }}/pipelines/training.py"]
